"""Build offline Swift data, Xcode image sets and a preview from the reviewed catalog.

Run from any directory: python scripts/generate-account-templates.py [--check]
Standard library only. No network access and no source asset modification.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets/account-templates/catalog.json"
ASSETS = ROOT / "App/Assets.xcassets/AccountBrands"
GROUPS = {"wallet": "支付钱包", "bank": "银行卡", "creditCard": "信用卡", "storedValue": "话费与储值", "cash": "现金"}


def quoted(value: str) -> str:
    # JSON quoting agrees with Swift for these strings; disallow incompatible Unicode escapes.
    return json.dumps(value, ensure_ascii=False).replace("\\/", "/")


def string_array(values: list[str]) -> str:
    return "[" + ", ".join(quoted(value) for value in values) + "]"


def validate(data: dict) -> None:
    assert data["schemaVersion"] == 1 and data["region"] == "CN"
    for field in ("icons", "institutions", "templates"):
        identifiers = [item["id"] for item in data[field]]
        assert len(identifiers) == len(set(identifiers)), f"Duplicate {field} ID"
        assert all(re.fullmatch(r"[a-z0-9.-]+", key) for key in identifiers)
    icons = {item["id"]: item for item in data["icons"]}
    institutions = {item["id"]: item for item in data["institutions"]}
    asset_names = [item["assetName"] for item in icons.values() if item["assetName"]]
    assert len(asset_names) == len(set(asset_names)), "Duplicate asset name"
    for icon in icons.values():
        assert re.fullmatch(r"#[0-9A-Fa-f]{6}", icon["colorHex"])
        assert icon["fallbackSymbol"] and icon["accessibilityName"]
        if not icon["assetName"]:
            assert not icon.get("filePath"), "Generic icons use SF Symbols"
            continue
        assert re.fullmatch(r"account-brand-[a-z0-9-]+", icon["assetName"])
        path = (ROOT / icon["filePath"]).resolve()
        assert path.is_relative_to(DATA.parent), "Source asset escaped catalog directory"
        content = path.read_bytes()
        assert hashlib.sha256(content).hexdigest() == icon["sha256"], f"Changed source: {path}"
        assert icon["sourceURL"].startswith("https://") and icon["usageNote"]
        if path.suffix == ".svg":
            svg = ET.fromstring(content)
            assert svg.tag.split("}")[-1] == "svg" and svg.get("viewBox")
            for element in svg.iter():
                assert element.tag.split("}")[-1] not in {"script", "foreignObject", "image", "text"}
                for key, value in element.attrib.items():
                    assert not key.lower().startswith("on"), "Event handlers are not allowed"
                    assert "url(" not in value or "url(#" in value, "External SVG resource"
                    if key.split("}")[-1] == "href":
                        assert value.startswith("#"), "External SVG link"
        else:
            assert path.suffix == ".png" and content.startswith(b"\x89PNG\r\n\x1a\n")
    for institution in institutions.values():
        assert institution["iconID"] in icons
    for template in data["templates"]:
        assert template["group"] in GROUPS and template["iconID"] in icons
        assert template["currency"] == "CNY" and type(template["includedInSummary"]) is bool
        assert template["kind"] in {"wallet", "bank", "creditCard", "storedValue", "cash"}
        assert template["nature"] == ("liability" if template["kind"] == "creditCard" else "asset")
        if template["institutionID"]:
            institution = institutions[template["institutionID"]]
            assert institution["iconID"] == template["iconID"]
        if "话费" in template["name"]:
            assert template["kind"] == "storedValue" and not template["includedInSummary"]


def swift(data: dict) -> str:
    lines = ["// Generated by scripts/generate-account-templates.py; edit assets/account-templates/catalog.json.",
             "// This catalog is opt-in presentation data, never a seed account list.",
             "public enum AccountTemplateCatalog {", "    public static let region = \"CN\"", "    public static let icons: [AccountIcon] = ["]
    for item in data["icons"]:
        asset = quoted(item["assetName"]) if item["assetName"] else "nil"
        lines.append(f'        AccountIcon(id: {quoted(item["id"])}, assetName: {asset}, fallbackSymbol: {quoted(item["fallbackSymbol"])}, colorHex: {quoted(item["colorHex"])}, accessibilityName: {quoted(item["accessibilityName"])}),')
    lines += ["    ]", "", "    public static let institutions: [AccountInstitution] = ["]
    for item in data["institutions"]:
        lines.append(f'        AccountInstitution(id: {quoted(item["id"])}, name: {quoted(item["name"])}, shortName: {quoted(item["shortName"])}, aliases: {string_array(item["aliases"])}, iconID: {quoted(item["iconID"])}),')
    lines += ["    ]", "", "    public static let templates: [AccountTemplate] = ["]
    for item in data["templates"]:
        institution = quoted(item["institutionID"]) if item["institutionID"] else "nil"
        lines += [f'        AccountTemplate(id: {quoted(item["id"])}, name: {quoted(item["name"])}, group: .{item["group"]},',
                  f'                        institutionID: {institution}, iconID: {quoted(item["iconID"])}, kind: .{item["kind"]}, nature: .{item["nature"]},',
                  f'                        currency: .cny, includedInSummary: {str(item["includedInSummary"]).lower()}, keywords: {string_array(item["keywords"])},',
                  f'                        note: {quoted(item["note"])}),']
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def preview(data: dict) -> str:
    esc = html.escape
    cards = []
    for icon in data["icons"]:
        if not icon["assetName"]:
            continue
        relative = Path(icon["filePath"]).relative_to("assets/account-templates").as_posix()
        source = esc(icon["sourceURL"], quote=True)
        cards.append(f'<article class="brand"><div class="sample"><div class="logo"><img src="{esc(relative)}" alt=""></div><div class="dark"><img src="{esc(relative)}" alt=""></div></div><strong>{esc(icon["accessibilityName"])}</strong><code>{esc(icon["id"])}</code><a href="{source}">图标出处 ↗</a></article>')
    rows = []
    icons = {icon["id"]: icon for icon in data["icons"]}
    institutions = {item["id"]: item for item in data["institutions"]}
    for item in data["templates"]:
        icon = icons[item["iconID"]]
        if icon.get("filePath"):
            relative = Path(icon["filePath"]).relative_to("assets/account-templates").as_posix()
            thumb = f'<img src="{esc(relative)}" alt="">'
        else:
            thumb = f'<span class="generic">{esc({"cash":"¥", "creditCard":"卡", "bank":"行", "storedValue":"储", "wallet":"钱"}[item["kind"]])}</span>'
        institution = institutions.get(item["institutionID"], {})
        keywords = " ".join([item["name"], item["id"], institution.get("name", ""), institution.get("shortName", ""), *item["keywords"], *institution.get("aliases", [])]).lower()
        rows.append(f'<tr data-group="{item["group"]}" data-search="{esc(keywords, quote=True)}"><td><div class="template-name">{thumb}<div><strong>{esc(item["name"])}</strong><code>{item["id"]}</code></div></div></td><td>{GROUPS[item["group"]]}</td><td>{"负债" if item["nature"] == "liability" else "资产"} · CNY</td><td>{"计入" if item["includedInSummary"] else "不计入"}</td><td class="note">{esc(item["note"])}</td></tr>')
    filters = '<option value="">全部类型</option>' + ''.join(f'<option value="{key}">{value}</option>' for key, value in GROUPS.items())
    page = '''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>国内资产图标与模板 · Ledger</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#1d2433;font:15px/1.6 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1240px;margin:48px auto;padding:0 28px 64px}.eyebrow{color:#576477;font-size:12px;letter-spacing:.12em}h1{font-size:34px;letter-spacing:-.04em;margin:10px 0}h2{font-size:21px;margin:38px 0 16px}.intro{max-width:850px;color:#5b6471} .stats{display:flex;gap:12px;margin:24px 0}.stats span{background:white;border:1px solid #e3e6eb;border-radius:10px;padding:10px 18px}.stats b{margin-right:6px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(165px,1fr));gap:12px}.brand{padding:18px;background:white;border:1px solid #e3e6eb;border-radius:12px}.sample{display:flex;align-items:center;gap:12px;margin-bottom:12px}.logo,.dark{width:54px;height:54px;border-radius:12px;display:grid;place-items:center}.logo{border:1px solid #eaedf1;background:white}.dark{background:#202733}.sample img{width:36px;height:36px;object-fit:contain;background:white;border-radius:5px;padding:3px}.brand strong{display:block;font-size:14px}code{display:block;font-size:10px;color:#718096;overflow-wrap:anywhere}.brand a{font-size:11px;color:#416392;text-decoration:none}.controls{display:flex;gap:12px;margin-bottom:16px}input,select{font:inherit;border:1px solid #d5dbe4;border-radius:8px;background:white;padding:10px 12px}input{flex:1;min-width:100px}.table-wrap{overflow:auto;background:white;border:1px solid #e3e6eb;border-radius:12px}table{border-collapse:collapse;width:100%;min-width:850px}th,td{text-align:left;padding:16px;border-bottom:1px solid #edf0f4}th{background:#fafbfc;font-size:12px;color:#657186}td{font-size:13px}.template-name{display:flex;align-items:center;gap:12px;min-width:180px}.template-name img,.generic{width:32px;height:32px;object-fit:contain;flex-shrink:0}.generic{background:#edf1f6;color:#5e6e82;border-radius:8px;display:grid;place-items:center}.note{max-width:300px;color:#647185;font-size:12px}.foot{font-size:12px;color:#68778a;margin-top:24px}.empty{display:none;padding:24px;text-align:center;color:#657186}@media(max-width:600px){main{padding:0 16px;margin-top:28px}h1{font-size:27px}.stats{flex-wrap:wrap}.controls{flex-wrap:wrap}}</style></head><body><main>
<div class="eyebrow">LEDGER / CHINA ACCOUNT CATALOG</div><h1>国内资产图标与模板</h1><p class="intro">为新增、编辑账户准备的本地素材库。品牌标志独立复用，账户模板区分余额与负债；所有模板默认人民币。白色小底板保持标志在浅色、深色界面中的辨识度。</p>
<div class="stats"><span><b>__BRANDS__</b>机构标志</span><span><b>__TEMPLATES__</b>账户模板</span><span><b>CNY</b>默认币种</span></div>
<h2>机构标志</h2><div class="grid">__CARDS__</div>
<h2>账户模板</h2><div class="controls"><input id="query" aria-label="搜索模板" placeholder="搜索微信、工行、ICBC、移动话费…"><select id="group" aria-label="账户类型">__FILTERS__</select></div>
<div class="table-wrap"><table><thead><tr><th>模板 / 稳定 ID</th><th>分组</th><th>性质 / 币种</th><th>资产负债汇总</th><th>使用说明</th></tr></thead><tbody>__ROWS__</tbody></table><div class="empty" id="empty">没有匹配的模板</div></div>
<p class="foot">本页为素材预览，模板尚未接入账户页面。编辑已有账户时保留账户 ID、类型、性质、币种、期初与汇总选择；图标使用独立 ID，不凭名称自动判断。品牌资源出处与使用状态记录在 catalog.json 和相应 sources.json 中。通用模板在 iOS 使用 SF Symbols，本页以文字小标识展示。</p>
</main><script>const rows=[...document.querySelectorAll('tbody tr')];function filter(){const words=document.getElementById('query').value.normalize('NFKC').trim().toLowerCase().split(/\\s+/).filter(Boolean);const group=document.getElementById('group').value;let count=0;for(const row of rows){const show=(!group||row.dataset.group===group)&&words.every(w=>row.dataset.search.includes(w));row.hidden=!show;if(show)count++}document.getElementById('empty').style.display=count?'none':'block'}document.getElementById('query').addEventListener('input',filter);document.getElementById('group').addEventListener('change',filter);</script></body></html>'''
    return page.replace("__BRANDS__", str(len(cards))).replace("__TEMPLATES__", str(len(rows))).replace("__CARDS__", "".join(cards)).replace("__FILTERS__", filters).replace("__ROWS__", "".join(rows))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate inputs and detect stale generated files")
    args = parser.parse_args()
    data = json.loads(DATA.read_text(encoding="utf-8"))
    validate(data)
    contents = {"info": {"author": "xcode", "version": 1}}
    generated: dict[Path, bytes] = {}

    def add(path: Path, value: str | dict | bytes) -> None:
        if isinstance(value, dict):
            value = json.dumps(value, ensure_ascii=False, indent=2) + "\n"
        generated[path] = value.encode("utf-8") if isinstance(value, str) else value

    add(ROOT / "Sources/LedgerCore/AccountTemplateCatalog.swift", swift(data))
    add(DATA.parent / "preview.html", preview(data))
    add(ASSETS / "Contents.json", contents)
    # Do not take ownership of a pre-existing application's asset catalog root.
    if not (ASSETS.parent / "Contents.json").exists():
        add(ASSETS.parent / "Contents.json", contents)
    for icon in data["icons"]:
        if not icon["assetName"]:
            continue
        source = ROOT / icon["filePath"]
        image_set = ASSETS / (icon["assetName"] + ".imageset")
        add(image_set / source.name, source.read_bytes())
        image_contents = {"images": [{"filename": source.name, "idiom": "universal"}], **contents,
                          "properties": {"template-rendering-intent": "original"}}
        if source.suffix == ".svg":
            image_contents["properties"]["preserves-vector-representation"] = True
        add(image_set / "Contents.json", image_contents)
    stale = []
    for path, content in generated.items():
        if args.check:
            if not path.is_file() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    unexpected = [str(path.relative_to(ROOT)) for path in ASSETS.rglob("*") if path.is_file() and path not in generated]
    if stale or unexpected:
        raise SystemExit("Generated assets need review:\n" + "\n".join(stale + unexpected))
    print(f'{"Checked" if args.check else "Generated"}: {len(data["institutions"])} institutions, {len(data["templates"])} templates, {len(generated)} files.')


if __name__ == "__main__":
    main()
